apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-reader
  labels:
    app: migration
spec:
  selector:
    matchLabels:
      logreader: mig
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: migration
        logreader: mig
    spec:
      containers:
        - name: color
          image: 'quay.io/djwhatle/mig-log-reader:latest'
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/cache/sa2kubeconfig
              name: kubeconfig
          env:
            - name: STERN_COLOR
              value: always
            - name: KSUFFIX
              value: color

        - name: plain
          image: 'quay.io/djwhatle/mig-log-reader:latest'
          imagePullPolicy: Always
          volumeMounts:
            - mountPath: /var/cache/sa2kubeconfig
              name: kubeconfig
          env:
            - name: STERN_COLOR
              value: never
            - name: KSUFFIX
              value: plain

      serviceAccountName: migration-controller
      volumes:
      - emptyDir: {}
        name: kubeconfig